### ISSUE TITLE
Jakarta EE 10 Javadoc search feature not working

### ISSUE THREAD

**Issue by cypher256** [jakartaee/jakartaee-api#141]
Windows 11 Pro: Chrome, Edge
macOS Sonoma: Chrome, Safari

Searching from the top right of Jakarta EE 10 Javadoc (e.g. "HttpServlet") and clicking on the resulting class always results in an http 404 error.

https://jakarta.ee/specifications/platform/10/apidocs
Example search word: "HttpServlet"

Clicking it will jump to a URL that includes "undefined" as shown below.
https://jakarta.ee/specifications/platform/10/apidocs/undefined/jakarta/servlet/http/HttpServlet.html

**Comment by lprimak** [comment]
This is now fixed. This issue can be closed.

**Comment by lprimak** [comment]
@ivargrimstad @edburns Please close this issue. Thank you!
