### ISSUE TITLE
Resolve failing build

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/jakartaee-api#172]
The api build is currently failing.

https://ci.eclipse.org/jakartaee-platform/job/1_jakartaee-api-main-SNAPHOT/

Need some help figuring this out to be able to release Core Profile API and JavaDoc.

**Comment by ivargrimstad** [comment]
Is this something you can look at @lprimak? You've been so helpful before ;)

**Comment by lprimak** [comment]
Looks like a Faces issue. @arjantijms

**Comment by lprimak** [comment]
Jakarta.ws module needs to be removed from module-info

**Comment by ivargrimstad** [comment]
So we would need a service release of faces, or potentially replace the module-info for faces when unpacking the jar as we did previously?

A temprary fix by Jared to add back the ws dependency has been made in #173

**Comment by ivargrimstad** [comment]
> So we would need a service release of faces, or potentially replace the module-info for faces when unpacking the jar as we did previously?
> 
> A temprary fix by Jared to add back the ws dependency has been made in #173

It is not here as far as I can see:
https://github.com/jakartaee/faces/blob/master/api/src/main/module/module-info.java
So where does it come from?

**Comment by lprimak** [comment]
Ok, I see what's happening:

- ` jakarta.faces-api` version 4.1.1 was never released
- ` jakarta.faces-api` version 4.1.1 needs to be releaed
- `jakartaee-api` needs to be upgraded to faces-api version 4.1.1
- https://github.com/jakartaee/jakartaee-api/pull/173 needs to be reverted

@balusc @arjantijms :)

**Comment by arjantijms** [comment]
4.1.1 of the Faces API has been staged here: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/faces/jakarta.faces-api/4.1.1/

It was build and extracted from Mojarra 4.1.2.

**Comment by lprimak** [comment]
Awesome!
I re-tested the build with the new APIs and it works!

* Revert https://github.com/jakartaee/jakartaee-api/pull/173
* Update faces-api to 4.1.1

```
[INFO] Reactor Summary for Jakarta EE API parent 11.0.0-SNAPSHOT:
[INFO] 
[INFO] Jakarta EE API parent .............................. SUCCESS [  0.984 s]
[INFO] Jakarta EE API BOM ................................. SUCCESS [  0.132 s]
[INFO] Jakarta EE Core Profile API ........................ SUCCESS [ 42.338 s]
[INFO] Jakarta EE Web Profile API ......................... SUCCESS [01:28 min]
[INFO] Jakarta EE Platform API ............................ SUCCESS [02:27 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by lprimak** [comment]
Created PR that should take care of everything @ivargrimstad
